---

#GENESISFILE required
#CONFIGFILE required
#BINARY required

- hosts: all
  any_errors_fatal: true
  gather_facts: no
  roles:
    - increase-openfiles
    - set-tcp-tw-reuse
    - setup-fullnodes

