---

- name: Copy binary
  copy:
    src: "{{THORCHAINCLI_BINARY}}"
    dest: /usr/bin/thorchaincli
    mode: 0755
  notify: restart thorchaincli

- name: Copy service
  template:
    src: thorchaincli.service.j2
    dest: /etc/systemd/system/thorchaincli.service
  notify: systemctl

