---

#Note: You need to add LOGZIO_TOKEN variable with your API key. Like this: ansible-playbook -e LOGZIO_TOKEN=ABCXYZ123456

- hosts: all
  remote_user: ec2-user
  become: yes
  any_errors_fatal: true
  gather_facts: no
  vars:
    - service: thorchainspam
    - JOURNALBEAT_BINARY: "{{lookup('env', 'GOPATH')}}/bin/journalbeat"
  roles:
    - logzio

